name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:
    inputs:
      retain_days:
        description: 'Days to retain runs'
        required: true
        default: '7'
      keep_minimum_runs:
        description: 'Minimum runs to keep per workflow'
        required: true
        default: '3'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.retain_days || 7 }}
          keep_minimum_runs: ${{ inputs.keep_minimum_runs || 3 }}
